### PR TITLE
Use a static class - avoid re-reading files etc

### PR DESCRIPTION
**Pull request by GlazerMann**
This is just a significant performance increase.

### CODE REVIEW

**Comment by GlazerMann** [comment]
Probably better long term to make the included files a const array instead of a return, but that would require reworking the updater tool also.

**Comment by clemlatz** [comment]
Hey @GlazerMann, thanks for your contribution and sorry for taking so long to get back to you.

If you're still willing to support this PR, could you make sure tests are passing ? I'm seeing several failing because of a parse error.

**Comment by GlazerMann** [comment]
@clemlatz - still interested.  Looking at fixing.  Just fell off radar

**Comment by GlazerMann** [comment]
@clemlatz looks like pull need "approved" to run tests.  Once I see outcomes, I will fixed as needed.

**Comment by GlazerMann** [comment]
Thank you @clemlatz, my bug was stupid.  Fixed it.

**Pull request merged**
