### PR TITLE
Gracefully exiting if range API is unavailable

### LINKED ISSUE #23: Problem updating ranges
// **Update:** The ISBN page currently is unavailable due to maintenance:

image

In case the XML format / syntax changes, I'll notify you again - sorry for bothering!

// Original message

Hey there,
it seems that with PHP v7.4 (in my case 7.4.11) the update script throws a great many errors:

```text
❯ composer run update-ranges
> php bin/update-ranges.php
Requesting range information...
Getting XML from https://www.isbn-international.org/?q=download_range//...
PHP Notice:  Trying to get property 'result' of non-object in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 30
PHP Notice:  Trying to get property 'value' of non-object in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 30
PHP Notice:  Trying to get property 'result' of non-object in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 31
PHP Notice:  Trying to get property 'filename' of non-object in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 31
Converting to PHP array...
PHP Warning:  simplexml_load_string(): Entity: line 48: parser error : Opening and ending tag mismatch: meta line 4 and head in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): </head> in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():        ^ in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): Entity: line 61: parser error : Opening and ending tag mismatch: img line 4 and a in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():                 </a> in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():                     ^ in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): Entity: line 62: parser error : Opening and ending tag mismatch: a line 4 and div in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():             </div> in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():                   ^ in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): Entity: line 89: parser error : Opening and ending tag mismatch: div line 4 and body in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): </body></html> in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():        ^ in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): Entity: line 89: parser error : Opening and ending tag mismatch: body line 4 and html in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): </body></html> in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():               ^ in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): Entity: line 90: parser error : EndTag: '</' not found in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string():  in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Warning:  simplexml_load_string(): ^ in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 39
PHP Notice:  Undefined index: EAN.UCCPrefixes in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 43
PHP Notice:  Trying to access array offset on value of type null in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 43
PHP Notice:  Undefined index: RegistrationGroups in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 44
PHP Notice:  Trying to access array offset on value of type null in /path/to/project/vendor/biblys/isbn/bin/update-ranges.php on line 44
Saving to /path/to/project/vendor/biblys/isbn/bin/../src/Biblys/Isbn/ranges-array.php...
```

This results in an empty `ranges-array.php` file:

```php
<?php
/*
 * This file is generated automatically by update-ranges.php, do not edit
 * manually! See README.md for more info. 
 *
 * This file is part of the biblys/isbn package.
 *
 * (c) Clément Bourgoin
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

$groups = array (
);
$prefixes = array (
);
```

I'll have a look at this later, or maybe you beat me to it? :fox_face: 

Cheers,
S1SYPHOS

Composer **v1.10.13**
PHP **v7.4.11**

### PR DESCRIPTION
**Pull request by S1SYPHOS**
This fixes #23, so when updating ISBN ranges isn't possible (maintenance mode, etc), the script tells us exactly that.

### CODE REVIEW

**Comment by iwazaru** [comment]
@S1SYPHOS Looks great, thanks! Could you just add the site url in the error message (eg "The API at https://.. is unavailable") so users can easily check what's going on?

**Comment by S1SYPHOS** [comment]
Will do!

**Comment by S1SYPHOS** [comment]
@iwazaru I added the URL as requested - merge time!

**Comment by S1SYPHOS** [comment]
@iwazaru Should I make any more changes?

**Comment by iwazaru** [comment]
Sorry, I hadn't time to look at it earlier. It's now merged and released. Thanks for your help 👌🏻

**Comment by S1SYPHOS** [comment]
Sure thing, anytime! Your library came to the rescue for me, really. Glad to contribute!

**Comment by S1SYPHOS** [comment]
Maybe release a new patch release? Or did that already happen ;)

**Pull request merged**
